services:

  postgres:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    container_name: my-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3-alpine
    container_name: redis
    hostname: localhost
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 # management tool
  liquibase:
    container_name: liquibase
    image: liquibase:latest
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    volumes:
      - ./database/changelog/:/liquibase/changelog/
    command:
      update --username=postgres --password=postgres --changeLogFile=/changelog/changelog.xml --url=jdbc:postgresql://postgres:5432/postgres