spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: kladvirov@gmail.com
    password: ksme nqlr fwmf pawh
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        smtp:
          auth: true